data:extend({
  {
    type = "bool-setting",
    name = "steamTrains_enable_legacy",
    order = "A",
    setting_type = "startup",
    default_value = false
  },
  {
    type = "double-setting",
    name = "steamTrains_steam_accel_mult",
    order = "BA1",
    setting_type = "startup",
    default_value = 1.2,
    minimum_value = 0,
  },
  {
    type = "double-setting",
    name = "steamTrains_steam_topspeed_mult",
    order = "BA2",
    setting_type = "startup",
    default_value = 1.05,
    minimum_value = 0,
  },
  {
    type = "double-setting",
    name = "steamTrains_mixed_steam_accel_mult",
    order = "BB1",
    setting_type = "startup",
    default_value = 1.4,
    minimum_value = 0,
  },
  {
    type = "double-setting",
    name = "steamTrains_mixed_steam_topspeed_mult",
    order = "BB2",
    setting_type = "startup",
    default_value = 1.05,
    minimum_value = 0,
  },
  {
    type = "double-setting",
    name = "steamTrains_hot_steam_accel_mult",
    order = "BC1",
    setting_type = "startup",
    default_value = 1.5,
    minimum_value = 0,
  },
  {
    type = "double-setting",
    order = "BC2",
    name = "steamTrains_hot_steam_topspeed_mult",
    setting_type = "startup",
    default_value = 1.1,
    minimum_value = 0,
  },
})
